### ISSUE TITLE
APIError: The collection with slug media can't be found

### ISSUE THREAD

**Issue by 58bits** [AlessioGr/payload-plugin-lexical#25]
Was looking at the demo app in this repo, and when trying to save a post  with an image / upload in the post in the `LexicalMinimal` collection I receive the following error:

[02:55:34] ERROR (payload): APIError: The collection with slug media can't be found.
    at new ExtendableError (/home/tony/Projects/payload/payload-plugin-lexical-fork/node_modules/payload/src/errors/APIError.ts:26:11)
    at new APIError (/home/tony/Projects/payload/payload-plugin-lexical-fork/node_modules/payload/src/errors/APIError.ts:43:5)
    at findByIDLocal (/home/tony/Projects/payload/payload-plugin-lexical-fork/node_modules/payload/src/collections/operations/local/findByID.ts:48:11)
    at Payload.findByID (/home/tony/Projects/payload/payload-plugin-lexical-fork/node_modules/payload/src/payload.ts:255:12)
    at loadUploadData (/home/tony/Projects/payload/payload-plugin-lexical-fork/src/fields/LexicalAfterReadHook.ts:48:24)
    at traverseLexicalField (/home/tony/Projects/payload/payload-plugin-lexical-fork/src/fields/LexicalAfterReadHook.ts:80:30)
    at traverseLexicalField (/home/tony/Projects/payload/payload-plugin-lexical-fork/src/fields/LexicalAfterReadHook.ts:108:30)
    at populateLexicalRelationships (/home/tony/Projects/payload/payload-plugin-lexical-fork/src/fields/LexicalAfterReadHook.ts:35:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/tony/Projects/payload/payload-plugin-lexical-fork/demo/node_modules/payload/src/fields/hooks/afterRead/promise.ts:173:31

<img width="945" alt="image" src="https://user-images.githubusercontent.com/405612/235280438-974d2c63-304e-4d7d-97f9-f6849a1375fb.png">

**Comment by AlessioGr** [comment]
Hmmmm - you're totally right, I could reproduce that. I'm pretty sure this issue only happens in the demo, not when you actually install the plugin.
Prob some issue with the way I set up the dependencies / project structure. Will have a look!

**Comment by AlessioGr** [comment]
Should be fixed now!
