### ISSUE TITLE
update lexical to 0.11.1

### ISSUE THREAD

**Issue by timofei-iatsenko** [AlessioGr/payload-plugin-lexical#40]
I tried to update it locally via yarn's resolutions, but it seems there are breaking changes between current and latest version. 

> TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/tim/projects/roadtravel-main-landing/backend/node_modules/payload-plugin-lexical/src/features/emojipicker/plugins/index.tsx:26:27)

**Comment by AlessioGr** [comment]
> I tried to update it locally via yarn's resolutions, but it seems there are breaking changes between current and latest version.
> 
> > TypeError: Class extends value undefined is not a constructor or null
> > at Object. (/Users/tim/projects/roadtravel-main-landing/backend/node_modules/payload-plugin-lexical/src/features/emojipicker/plugins/index.tsx:26:27)

oh yea, updating needs some extra work. Usually, I go through each commit of the lexical playground and copy the relevant stuff they changed there.

Will do that once I find time! Don't think there have been any _too_ exciting changes anyways

**Comment by timofei-iatsenko** [comment]
I personally encountered a problem on our project. When a document has tables inside in some circumstances copy/paste stop working. When you trying to copy it show some not very useful error in console and all further processing is stopped. So i decided to check on new version first and that report a bug if it doesn't fixed in upstream.

**Comment by AlessioGr** [comment]
> I personally encountered a problem on our project. When a document has tables inside in some circumstances copy/paste stop working. When you trying to copy it show some not very useful error in console and all further processing is stopped. So i decided to check on new version first and that report a bug if it doesn't fixed in upstream.

Yep, that's https://github.com/AlessioGr/payload-plugin-lexical/issues/5. Already reported the bug upstream - sadly it has not been fixed in the latest version yet.

There's an open PR which fixes the issue, also linked in the upstream issue, but it's currently stalled. Might have to check it out and finish it myself

**Comment by timofei-iatsenko** [comment]
i saw this issue, but i think it's a different one. Firstly i have only one editor on the page, secondly the error message is different.
