### ISSUE TITLE
Using lexicalRichTextField in a Payload field type 'array' causing undefined reading 'type' properties error

### ISSUE THREAD

**Issue by georgeharito** [AlessioGr/payload-plugin-lexical#44]
It seems that Lexical loads up fine if it's at the starting/root level of the `fields` property in a `CollectionConfig`, but using `lexicalRichTextField()` as a sub-element in a field of type `array` causes the following error to appear on screen: 

```
Cannot read properties of undefined (reading 'type')
```

In Developer Tools console, the following error appears:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at $parseSerializedNodeImpl (Lexical.dev.js:7526:1)
    at parseEditorState (Lexical.dev.js:7577:1)
    at LexicalEditor.parseEditorState (Lexical.dev.js:10791:1)
    at initializeEditor (LexicalComposer.dev.js:106:1)
    at LexicalComposer.dev.js:66:1
    at mountMemo (react-dom.development.js:17225:1)
    at Object.useMemo (react-dom.development.js:17670:1)
    at Object.useMemo (react.development.js:1650:1)
    at LexicalComposer (LexicalComposer.dev.js:46:1)
    at renderWithHooks (react-dom.development.js:16305:1)
```

For example, using `lexicalRichTextField()` as such, works OK:

```
const Posts: CollectionConfig = {
    slug: 'posts',
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true,
        },
        lexicalRichTextField({
            name: 'content', 
            label: 'Content',
        }),
    ]
};

```

... but doing the following causes the error: 

```
const Posts: CollectionConfig = {
    slug: 'posts',
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true,
        },
        {
            name: 'columns',
            type: 'array', 
            minRows: 1, 
            maxRows: 2, 
            labels: {
                singular: 'Column', 
                plural: 'Columns', 
            },
            fields: [
                lexicalRichTextField({
                    name: 'content', 
                    label: 'Content',
                }),
            ],			
        },
    ]
};
```

(I've edited this comment to add some code examples).

**Comment by neverether** [comment]
+1
I'm seeing this happen when I have the lexical rich text field within a tag field as well. Using the top level seems to have no issues. It looks like configuration is not being passed along to the component when nested one level deep. Here's a my console errors:

```
Lexical.dev.js:10550 Uncaught Error: Node LinkNode has not been registered. Ensure node has been passed to createEditor.
    at LexicalEditor.registerMutationListener (Lexical.dev.js:10550:1)
    at LexicalAutoEmbedPlugin.dev.js:77:1
    at Array.map (<anonymous>)
    at LexicalAutoEmbedPlugin.dev.js:77:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
registerMutationListener @ Lexical.dev.js:10550
(anonymous) @ LexicalAutoEmbedPlugin.dev.js:77
(anonymous) @ LexicalAutoEmbedPlugin.dev.js:77
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
LexicalMarkdown.dev.js:778 Uncaught Error: MarkdownShortcuts: missing dependency for transformer. Ensure node dependency is included in editor initial config.
    at Object.registerMarkdownShortcuts (LexicalMarkdown.dev.js:778:1)
    at LexicalMarkdownShortcutPlugin.dev.js:46:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at performSyncWorkOnRoot (react-dom.development.js:26076:1)
registerMarkdownShortcuts @ LexicalMarkdown.dev.js:778
(anonymous) @ LexicalMarkdownShortcutPlugin.dev.js:46
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <LexicalAutoEmbedPlugin> component:

    at LexicalAutoEmbedPlugin (http://localhost:3000/admin/main.js:17525:3)
    at AutoEmbedPlugin (http://localhost:3000/admin/main.js:195979:32)
    at div
    at Editor (http://localhost:3000/admin/main.js:192874:13)
    at div
    at CommentsContext (http://localhost:3000/admin/main.js:197049:28)
    at SharedAutocompleteContext (http://localhost:3000/admin/main.js:193390:38)
    at TableContext (http://localhost:3000/admin/main.js:199421:25)
    at SharedHistoryContext (http://localhost:3000/admin/main.js:193473:33)
    at EditorConfigContext (http://localhost:3000/admin/main.js:192770:32)
    at LexicalComposer (http://localhost:3000/admin/main.js:18755:3)
    at LexicalEditor (http://localhost:3000/admin/main.js:192728:13)
    at LexicalEditorComponent (http://localhost:3000/admin/main.js:192757:13)
    at ErrorBoundary (http://localhost:3000/admin/main.js:270895:37)
    at div
    at div
    at LexicalRichTextFieldComponent2 (http://localhost:3000/admin/main.js:193078:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at Suspense
    at Field
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at div
    at TabsProvider (http://localhost:3000/admin/main.js:218734:25)
    at div
    at TabsField (http://localhost:3000/admin/main.js:218624:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at http://localhost:3000/admin/main.js:205350:13
    at div
    at E.t.Provider (http://localhost:3000/admin/main.js:319227:639)
    at form
    at Form (http://localhost:3000/admin/main.js:211193:13)
    at div
    at DefaultEditView (http://localhost:3000/admin/main.js:225008:81)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at EditView (http://localhost:3000/admin/main.js:225401:25)
    at DocumentInfoProvider (http://localhost:3000/admin/main.js:221213:33)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:220745:20)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:202723:64)
    at CustomProvider (http://localhost:3000/admin/main.js:221154:27)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:221582:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:208196:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:221714:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:222021:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:222086:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:221905:32)
    at AuthProvider (http://localhost:3000/admin/main.js:220840:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7857:29)
    at Router (http://localhost:3000/admin/main.js:275072:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:274177:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:9478:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:9755:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:221107:27)
    at Root

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <MarkdownShortcutPlugin> component:

    at MarkdownShortcutPlugin (http://localhost:3000/admin/main.js:19972:3)
    at MarkdownPlugin (http://localhost:3000/admin/main.js:198119:27)
    at div
    at Editor (http://localhost:3000/admin/main.js:192874:13)
    at div
    at CommentsContext (http://localhost:3000/admin/main.js:197049:28)
    at SharedAutocompleteContext (http://localhost:3000/admin/main.js:193390:38)
    at TableContext (http://localhost:3000/admin/main.js:199421:25)
    at SharedHistoryContext (http://localhost:3000/admin/main.js:193473:33)
    at EditorConfigContext (http://localhost:3000/admin/main.js:192770:32)
    at LexicalComposer (http://localhost:3000/admin/main.js:18755:3)
    at LexicalEditor (http://localhost:3000/admin/main.js:192728:13)
    at LexicalEditorComponent (http://localhost:3000/admin/main.js:192757:13)
    at ErrorBoundary (http://localhost:3000/admin/main.js:270895:37)
    at div
    at div
    at LexicalRichTextFieldComponent2 (http://localhost:3000/admin/main.js:193078:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at Suspense
    at Field
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at div
    at TabsProvider (http://localhost:3000/admin/main.js:218734:25)
    at div
    at TabsField (http://localhost:3000/admin/main.js:218624:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at http://localhost:3000/admin/main.js:205350:13
    at div
    at E.t.Provider (http://localhost:3000/admin/main.js:319227:639)
    at form
    at Form (http://localhost:3000/admin/main.js:211193:13)
    at div
    at DefaultEditView (http://localhost:3000/admin/main.js:225008:81)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at EditView (http://localhost:3000/admin/main.js:225401:25)
    at DocumentInfoProvider (http://localhost:3000/admin/main.js:221213:33)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:220745:20)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:202723:64)
    at CustomProvider (http://localhost:3000/admin/main.js:221154:27)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:221582:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:208196:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:221714:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:222021:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:222086:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:221905:32)
    at AuthProvider (http://localhost:3000/admin/main.js:220840:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7857:29)
    at Router (http://localhost:3000/admin/main.js:275072:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:274177:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:9478:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:9755:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:221107:27)
    at Root

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Lexical.dev.js:10550 Uncaught Error: Node LinkNode has not been registered. Ensure node has been passed to createEditor.
    at LexicalEditor.registerMutationListener (Lexical.dev.js:10550:1)
    at LexicalAutoEmbedPlugin.dev.js:77:1
    at Array.map (<anonymous>)
    at LexicalAutoEmbedPlugin.dev.js:77:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
registerMutationListener @ Lexical.dev.js:10550
(anonymous) @ LexicalAutoEmbedPlugin.dev.js:77
(anonymous) @ LexicalAutoEmbedPlugin.dev.js:77
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
LexicalMarkdown.dev.js:778 Uncaught Error: MarkdownShortcuts: missing dependency for transformer. Ensure node dependency is included in editor initial config.
    at Object.registerMarkdownShortcuts (LexicalMarkdown.dev.js:778:1)
    at LexicalMarkdownShortcutPlugin.dev.js:46:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
registerMarkdownShortcuts @ LexicalMarkdown.dev.js:778
(anonymous) @ LexicalMarkdownShortcutPlugin.dev.js:46
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
react-dom.development.js:18687 The above error occurred in the <LexicalAutoEmbedPlugin> component:

    at LexicalAutoEmbedPlugin (http://localhost:3000/admin/main.js:17525:3)
    at AutoEmbedPlugin (http://localhost:3000/admin/main.js:195979:32)
    at div
    at Editor (http://localhost:3000/admin/main.js:192874:13)
    at div
    at CommentsContext (http://localhost:3000/admin/main.js:197049:28)
    at SharedAutocompleteContext (http://localhost:3000/admin/main.js:193390:38)
    at TableContext (http://localhost:3000/admin/main.js:199421:25)
    at SharedHistoryContext (http://localhost:3000/admin/main.js:193473:33)
    at EditorConfigContext (http://localhost:3000/admin/main.js:192770:32)
    at LexicalComposer (http://localhost:3000/admin/main.js:18755:3)
    at LexicalEditor (http://localhost:3000/admin/main.js:192728:13)
    at LexicalEditorComponent (http://localhost:3000/admin/main.js:192757:13)
    at ErrorBoundary (http://localhost:3000/admin/main.js:270895:37)
    at div
    at div
    at LexicalRichTextFieldComponent2 (http://localhost:3000/admin/main.js:193078:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at Suspense
    at Field
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at div
    at TabsProvider (http://localhost:3000/admin/main.js:218734:25)
    at div
    at TabsField (http://localhost:3000/admin/main.js:218624:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at http://localhost:3000/admin/main.js:205350:13
    at div
    at E.t.Provider (http://localhost:3000/admin/main.js:319227:639)
    at form
    at Form (http://localhost:3000/admin/main.js:211193:13)
    at div
    at DefaultEditView (http://localhost:3000/admin/main.js:225008:81)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at EditView (http://localhost:3000/admin/main.js:225401:25)
    at DocumentInfoProvider (http://localhost:3000/admin/main.js:221213:33)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:220745:20)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:202723:64)
    at CustomProvider (http://localhost:3000/admin/main.js:221154:27)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:221582:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:208196:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:221714:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:222021:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:222086:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:221905:32)
    at AuthProvider (http://localhost:3000/admin/main.js:220840:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7857:29)
    at Router (http://localhost:3000/admin/main.js:275072:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:274177:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:9478:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:9755:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:221107:27)
    at Root

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
react-dom.development.js:18687 The above error occurred in the <MarkdownShortcutPlugin> component:

    at MarkdownShortcutPlugin (http://localhost:3000/admin/main.js:19972:3)
    at MarkdownPlugin (http://localhost:3000/admin/main.js:198119:27)
    at div
    at Editor (http://localhost:3000/admin/main.js:192874:13)
    at div
    at CommentsContext (http://localhost:3000/admin/main.js:197049:28)
    at SharedAutocompleteContext (http://localhost:3000/admin/main.js:193390:38)
    at TableContext (http://localhost:3000/admin/main.js:199421:25)
    at SharedHistoryContext (http://localhost:3000/admin/main.js:193473:33)
    at EditorConfigContext (http://localhost:3000/admin/main.js:192770:32)
    at LexicalComposer (http://localhost:3000/admin/main.js:18755:3)
    at LexicalEditor (http://localhost:3000/admin/main.js:192728:13)
    at LexicalEditorComponent (http://localhost:3000/admin/main.js:192757:13)
    at ErrorBoundary (http://localhost:3000/admin/main.js:270895:37)
    at div
    at div
    at LexicalRichTextFieldComponent2 (http://localhost:3000/admin/main.js:193078:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at Suspense
    at Field
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at div
    at TabsProvider (http://localhost:3000/admin/main.js:218734:25)
    at div
    at TabsField (http://localhost:3000/admin/main.js:218624:13)
    at CheckForCondition (http://localhost:3000/admin/main.js:219504:24)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at div
    at RenderFields (http://localhost:3000/admin/main.js:211897:13)
    at div
    at http://localhost:3000/admin/main.js:205350:13
    at div
    at E.t.Provider (http://localhost:3000/admin/main.js:319227:639)
    at form
    at Form (http://localhost:3000/admin/main.js:211193:13)
    at div
    at DefaultEditView (http://localhost:3000/admin/main.js:225008:81)
    at RenderCustomComponent (http://localhost:3000/admin/main.js:221970:13)
    at EditView (http://localhost:3000/admin/main.js:225401:25)
    at DocumentInfoProvider (http://localhost:3000/admin/main.js:221213:33)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at div
    at div
    at Default (http://localhost:3000/admin/main.js:220745:20)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Switch (http://localhost:3000/admin/main.js:275655:29)
    at Route (http://localhost:3000/admin/main.js:275453:29)
    at Suspense
    at Routes (http://localhost:3000/admin/main.js:202723:64)
    at CustomProvider (http://localhost:3000/admin/main.js:221154:27)
    at LoadingOverlayProvider (http://localhost:3000/admin/main.js:221582:35)
    at StepNavProvider (http://localhost:3000/admin/main.js:208196:28)
    at LocaleProvider (http://localhost:3000/admin/main.js:221714:27)
    at SearchParamsProvider (http://localhost:3000/admin/main.js:222021:33)
    at ThemeProvider (http://localhost:3000/admin/main.js:222086:26)
    at PreferencesProvider (http://localhost:3000/admin/main.js:221905:32)
    at AuthProvider (http://localhost:3000/admin/main.js:220840:25)
    at ModalProvider (http://localhost:3000/admin/main.js:7857:29)
    at Router (http://localhost:3000/admin/main.js:275072:30)
    at BrowserRouter (http://localhost:3000/admin/main.js:274177:35)
    at ScrollInfoProvider (http://localhost:3000/admin/main.js:9478:26)
    at WindowInfoProvider (http://localhost:3000/admin/main.js:9755:29)
    at ConfigProvider (http://localhost:3000/admin/main.js:221107:27)
    at Root
```

**Comment by taismassaro** [comment]
I just installed the plugin for the first time and I'm having the same issue. @AlessioGr is there any workaround for this?
