### ISSUE TITLE
dependency issue, possible due to faulty misconfig

### ISSUE THREAD

**Issue by nikhil-swamix** [AlessioGr/payload-plugin-lexical#49]
### im using pnpm and i get this error
_____
Error: Cannot find module 'payload/dist/admin/components/forms/field-types/RichText/elements/link/LinkDrawer/baseFields'
Require stack:
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\features\linkplugin\floatingLinkEditor\index.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\features\linkplugin\LinkFeature.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\types.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\fields\lexicalRichTextField.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\index.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\src\payload\collections\Posts\index.ts
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\src\payload\payload.config.ts
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\node_modules\payload\dist\config\load.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\node_modules\payload\dist\bin\generateGraphQLSchema.js        
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\node_modules\payload\dist\bin\index.js
- D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\node_modules\payload\bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\node_modules\payload-plugin-lexical\dist\features\linkplugin\floatingLinkEditor\index.js:56:22)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.newLoader [as .js] (D:\GitHub\COMPANIES\bbp-himanshu\chunavexpress.com\backend\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\\node_modules\\payload-plugin-lexical\\dist\\features\\linkplugin\\floatingLinkEditor\\index.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\\node_modules\\payload-plugin-lexical\\dist\\features\\linkplugin\\LinkFeature.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\\node_modules\\payload-plugin-lexical\\dist\\types.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\\node_modules\\payload-plugin-lexical\\dist\\fields\\lexicalRichTextField.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload-plugin-lexical@0.6.6_payload@2.0.4_react-dom@18.2.0_react@18.2.0_yjs@13.6.8\\node_modules\\payload-plugin-lexical\\dist\\index.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\src\\payload\\collections\\Posts\\index.ts',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\src\\payload\\payload.config.ts',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\\node_modules\\payload\\dist\\config\\load.js',    
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\\node_modules\\payload\\dist\\bin\\generateGraphQLSchema.js',
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\\node_modules\\payload\\dist\\bin\\index.js',      
    'D:\\GitHub\\COMPANIES\\bbp-himanshu\\chunavexpress.com\\backend\\node_modules\\.pnpm\\payload@2.0.4_@types+react@18.0.21_typescript@4.9.5_webpack@5.88.2\\node_modules\\payload\\bin.js'
  ]
}

____
### HELP required.

**Comment by timofei-iatsenko** [comment]
Do you try to use it with payload 2? They are not compatible
